# 管理后台菜单配置，默认载入目录下所有yaml文件；新增角色后，只需在此文件同级目录下创建对应yaml文件，并设置数据库中角色字段abbrev与该文件中的标识名一致。
#    只支持两级菜单;二级菜单可用属性： name/href/rel/data-confirm/data-method

admin:
  - name: 权限管理
    menus:
      - name: 用户管理
        href: /admin/users
      - name: 权限角色
        href: /admin/roles
  - name: 活动管理
    menus:
      - name: 活动信息
        href: /admin/events
      - name: 活动报名
        href: /admin/applies
  - name: 答题管理
    menus:
      - name: 试题分类
        href: /admin/question_classifies
      - name: 试题
        href: /admin/questions
  - name: 分类管理
    menus:
      - name: 分类层级
        href: /admin/taxons
