# 管理后台菜单配置，默认载入目录下所有yaml文件；新增角色后，只需在此文件同级目录下创建对应yaml文件，并设置数据库中角色字段abbrev与该文件中的标识名一致。
#    只支持两级菜单;二级菜单可用属性： name/href/rel/data-confirm/data-method

admin:
  - name: 权限管理
    menus:
      - name: 管理员列表
        href: /admin/users
      - name: 权限角色
        href: /admin/roles
  - name: 视频管理
    menus:
      - name: 视频列表
        href: /admin/events
  - name: 报名管理
    menus:
      - name: 报名列表
        href: /admin/enlists
  - name: 用户管理
    menus: 
      - name: 用户列表
        href: /admin/players
  - name: 观看记录
    menus: 
      - name: 记录列表
        href: /admin/gensees
  - name: 页面内容定制
    menus: 
      - name: 定制列表
        href: /admin/contents
